/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostsRouteRouteImport } from './routes/posts/route'
import { Route as HpRouteRouteImport } from './routes/hp/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as HpIndexRouteImport } from './routes/hp/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'

const PostsRouteRoute = PostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const HpRouteRoute = HpRouteRouteImport.update({
  id: '/hp',
  path: '/hp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRouteRoute,
} as any)
const HpIndexRoute = HpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HpRouteRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hp': typeof HpRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/hp/': typeof HpIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/hp': typeof HpIndexRoute
  '/posts': typeof PostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hp': typeof HpRouteRouteWithChildren
  '/posts': typeof PostsRouteRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/hp/': typeof HpIndexRoute
  '/posts/': typeof PostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hp' | '/posts' | '/posts/$postId' | '/hp/' | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/posts/$postId' | '/hp' | '/posts'
  id:
    | '__root__'
    | '/'
    | '/hp'
    | '/posts'
    | '/posts/$postId'
    | '/hp/'
    | '/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HpRouteRoute: typeof HpRouteRouteWithChildren
  PostsRouteRoute: typeof PostsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hp': {
      id: '/hp'
      path: '/hp'
      fullPath: '/hp'
      preLoaderRoute: typeof HpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRouteRoute
    }
    '/hp/': {
      id: '/hp/'
      path: '/'
      fullPath: '/hp/'
      preLoaderRoute: typeof HpIndexRouteImport
      parentRoute: typeof HpRouteRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRouteRoute
    }
  }
}

interface HpRouteRouteChildren {
  HpIndexRoute: typeof HpIndexRoute
}

const HpRouteRouteChildren: HpRouteRouteChildren = {
  HpIndexRoute: HpIndexRoute,
}

const HpRouteRouteWithChildren =
  HpRouteRoute._addFileChildren(HpRouteRouteChildren)

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(
  PostsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HpRouteRoute: HpRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
